name: Deploy-Bookdown

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y pandoc texlive-latex-base
          R -e "install.packages(c('bookdown', 'rmarkdown'), repos='https://cloud.r-project.org')"

      - name: Render book
        run: |
          R -e "bookdown::render_book('index.Rmd')"

      - name: Rename output folder
        run: mv _book docs

      - name: Create .nojekyll file
        run: touch docs/.nojekyll  # ¡Esto es crucial!

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
