name: Deploy-Bookdown

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install pandoc and LaTeX
        run: |
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended

      - name: Install dependencies
        run: |
          R -e "install.packages(c('bookdown', 'rmarkdown', 'knitr', 'tidyverse'), repos='https://cran.rstudio.com')"

      - name: Render book
        run: |
          R -e "bookdown::render_book('index.Rmd', output_format = 'all')"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book  # Cambia a ./docs si usas esa carpeta
